# Generated by Django 3.1 on 2020-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201002_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_no',
            field=models.PositiveIntegerField(),
        ),
    ]
