# Generated by Django 3.0.7 on 2020-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201011_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
