# Generated by Django 3.1 on 2020-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201002_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_holder_name',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='account_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ifsc',
            field=models.TextField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
