# Generated by Django 3.1 on 2020-10-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0011_auto_20201011_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
