# Generated by Django 3.0.7 on 2020-10-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0014_auto_20201011_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
