# Generated by Django 3.0.7 on 2020-10-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0015_auto_20201011_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='phone_number',
        ),
    ]
