# Generated by Django 3.0.7 on 2020-10-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0016_remove_job_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
