# Generated by Django 3.0.7 on 2020-09-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_auto_20200919_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
    ]
