# Generated by Django 3.1 on 2020-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_remove_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='website',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
